# Generated by Django 5.0.3 on 2024-04-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updateed_at',
            new_name='updated_at',
        ),
    ]
